const ActionType = {
    //sign in
    START_SIGNIN: "START_SIGNIN",
    REMOVE_EMAIL_ERROR: "REMOVE_EMAIL_ERROR",
    REMOVE_PASSWORD_ERROR: "REMOVE_PASSWORD_ERROR",
    SIGNIN_SUCCESS: "SIGNIN_SUCCESS",
    SIGNIN_FAIL: "SIGNIN_FAIL",

    //sign up
    START_SIGNUP: "START_SIGNUP",
    REMOVE_EMAIL_SIGNUP_ERROR: "REMOVE_EMAIL_SIGNUP_ERROR",
    SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
    SIGNUP_FAIL: "SIGNUP_FAIL",

    //sign out
    LOGOUT: "LOGOUT",

    //get products
    START_GET_TOP_RATING: "START_GET_TOP_RATING",
    GET_TOP_RATING_SUCCESS: "GET_TOP_RATING_SUCCESS",
    GET_TOP_RATING_FAIL: "GET_TOP_RATING_FAIL",

    START_GET_LAPTOP_LIST: "START_GET_LAPTOP_LIST",
    GET_LAPTOP_LIST_SUCCESS: "GET_LAPTOP_LIST_SUCCESS",
    GET_LAPTOP_LIST_FAIL: "GET_LAPTOP_LIST_FAIL",

    START_GET_MONITOR_LIST: "START_GET_MONITOR_LIST",
    GET_MONITOR_LIST_SUCCESS: "GET_MONITOR_LIST_SUCCESS",
    GET_MONITOR_LIST_FAIL: "GET_MONITOR_LIST_FAIL",

    START_GET_CPU_LIST: "START_GET_CPU_LIST",
    GET_CPU_LIST_SUCCESS: "GET_CPU_LIST_SUCCESS",
    GET_CPU_LIST_FAIL: "GET_CPU_LIST_FAIL",
}
export default ActionType;

