const ActionType = {
    START_LOGIN: "START_LOGIN",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAIL: "LOGIN_FAIL",



    START_GET_PRODUCT_LIST: "START_GET_PRODUCT_LIST",
    GET_PRODUCT_LIST_SUCCESS: "GET_PRODUCT_LIST_SUCCESS",
    GET_PRODUCT_LIST_FAIL: "GET_PRODUCT_LIST_FAIL",
}
export default ActionType;

