const ActionType = {
	START_LOGIN: 'START_LOGIN',
	LOGIN_SUCCESS: 'LOGIN_SUCCESS',
	LOGIN_FAIL: 'LOGIN_FAIL',

	START_GET_TOP_RATING: 'START_GET_TOP_RATING',
	GET_TOP_RATING_SUCCESS: 'GET_TOP_RATING_SUCCESS',
	GET_TOP_RATING_FAIL: 'GET_TOP_RATING_FAIL',

	START_GET_LAPTOP_LIST: 'START_GET_LAPTOP_LIST',
	GET_LAPTOP_LIST_SUCCESS: 'GET_LAPTOP_LIST_SUCCESS',
	GET_LAPTOP_LIST_FAIL: 'GET_LAPTOP_LIST_FAIL',

	START_GET_MONITOR_LIST: 'START_GET_MONITOR_LIST',
	GET_MONITOR_LIST_SUCCESS: 'GET_MONITOR_LIST_SUCCESS',
	GET_MONITOR_LIST_FAIL: 'GET_MONITOR_LIST_FAIL',

	START_GET_CPU_LIST: 'START_GET_CPU_LIST',
	GET_CPU_LIST_SUCCESS: 'GET_CPU_LIST_SUCCESS',
	GET_CPU_LIST_FAIL: 'GET_CPU_LIST_FAIL',
};
export default ActionType;
